### ISSUE TITLE
"rake install" command can not run normally,why?

### ISSUE THREAD

**Issue by sangyongjia** [izenecloud/sf1r-lite#2] opened 2017-04-28 08:55 UTC
I installed ruby-1.9.3-p551 [ x86_64 ].
the environment is : CentOS release 6.8 (Final)

when I ran 'rake install' command  in driver-ruby folder as "http://izenecloud.github.io/sf1r/build/HowTo.html#id2" show.

**the error information as follows：**

[root@localhost driver-ruby]# rake install
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["bin/b5m-m-mail", "bin/b5m-monitor", "bin/b5mr-indexer"] are not files
ERROR:  Could not find a valid gem 'sf1-driver-3.0.0.gem' (>= 0) in any repository

any solutions?
Thanks

**Comment by dapicester** [comment] 2017-07-10 10:09
This seems a duplicate of #1

**Closed as completed** 2017-07-10 10:10 UTC
Labels: duplicate
